/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include "gomiMIB.hh"

#include <list>

/* Boost threading. */
#include <boost/thread/shared_mutex.hpp>

/* redirect namespace pollution */
#define U64 __netsnmp_U64

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* revert Net-snmp namespace pollution */
#undef U64
#define __netsnmp_LOG_EMERG	0
#define __netsnmp_LOG_ALERT	1
#define __netsnmp_LOG_CRIT	2
#define __netsnmp_LOG_ERR	3
#define __netsnmp_LOG_WARNING	4
#define __netsnmp_LOG_NOTICE	5
#define __netsnmp_LOG_INFO	6
#define __netsnmp_LOG_DEBUG	7
static_assert (__netsnmp_LOG_EMERG   == LOG_EMERG,   "LOG_EMERGE mismatch");
static_assert (__netsnmp_LOG_ALERT   == LOG_ALERT,   "LOG_ALERT mismatch");
static_assert (__netsnmp_LOG_CRIT    == LOG_CRIT,    "LOG_CRIT mismatch");
static_assert (__netsnmp_LOG_ERR     == LOG_ERR,     "LOG_ERR mismatch");
static_assert (__netsnmp_LOG_WARNING == LOG_WARNING, "LOG_WARNING mismatch");
static_assert (__netsnmp_LOG_NOTICE  == LOG_NOTICE,  "LOG_NOTICE mismatch");
static_assert (__netsnmp_LOG_INFO    == LOG_INFO,    "LOG_INFO mismatch");
static_assert (__netsnmp_LOG_DEBUG   == LOG_DEBUG,   "LOG_DEBUG mismatch");
#undef LOG_EMERG
#undef LOG_ALERT
#undef LOG_CRIT
#undef LOG_ERR
#undef LOG_WARNING
#undef LOG_NOTICE
#undef LOG_INFO
#undef LOG_DEBUG

#include "chromium/logging.hh"
#include "gomi.hh"
#include "provider.hh"
#include "session.hh"

namespace gomi {

/* http://en.wikipedia.org/wiki/Unix_epoch */
static const boost::posix_time::ptime kUnixEpoch (boost::gregorian::date (1970, 1, 1));

static int initialize_table_gomiPluginTable(void);
static Netsnmp_Node_Handler gomiPluginTable_handler;
static Netsnmp_First_Data_Point gomiPluginTable_get_first_data_point;
static Netsnmp_Next_Data_Point gomiPluginTable_get_next_data_point;
static Netsnmp_Free_Loop_Context gomiPluginTable_free_loop_context;

static int initialize_table_gomiPluginPerformanceTable(void);
static Netsnmp_Node_Handler gomiPluginPerformanceTable_handler;
static Netsnmp_First_Data_Point gomiPluginPerformanceTable_get_first_data_point;
static Netsnmp_Next_Data_Point gomiPluginPerformanceTable_get_next_data_point;
static Netsnmp_Free_Loop_Context gomiPluginPerformanceTable_free_loop_context;

static int initialize_table_gomiSessionTable(void);
static Netsnmp_Node_Handler gomiSessionTable_handler;
static Netsnmp_First_Data_Point gomiSessionTable_get_first_data_point;
static Netsnmp_Next_Data_Point gomiSessionTable_get_next_data_point;
static Netsnmp_Free_Loop_Context gomiSessionTable_free_loop_context;

static int initialize_table_gomiSessionPerformanceTable(void);
static Netsnmp_Node_Handler gomiSessionPerformanceTable_handler;
static Netsnmp_First_Data_Point gomiSessionPerformanceTable_get_first_data_point;
static Netsnmp_Next_Data_Point gomiSessionPerformanceTable_get_next_data_point;
static Netsnmp_Free_Loop_Context gomiSessionPerformanceTable_free_loop_context;

/* Context during a SNMP query, lock on global list of gomi_t objects and iterator.
 */
class snmp_context_t
{
public:
	snmp_context_t (boost::shared_mutex& lock_, std::list<gomi::gomi_t*>& list_) :
		lock (lock_),
		gomi_list (list_),
		gomi_it (gomi_list.begin())
	{
	}

/* Plugins are owned by AE, locking is required. */
	boost::shared_lock<boost::shared_mutex> lock;
	std::list<gomi::gomi_t*>& gomi_list;
	std::list<gomi::gomi_t*>::iterator gomi_it;
	std::vector<std::unique_ptr<gomi::session_t>>::iterator session_it;

/* SNMP agent is not-reentrant, ignore locking. */
	static std::list<std::shared_ptr<snmp_context_t>> global_list;
};

std::list<std::shared_ptr<snmp_context_t>> snmp_context_t::global_list;

/* Initializes the gomiMIB module.
 */
bool
init_gomiMIB(void)
{
/* here we initialize all the tables we're planning on supporting */
	if (MIB_REGISTERED_OK != initialize_table_gomiPluginTable()) {
		LOG(ERROR) << "gomiPluginTable registration: see SNMP log for further details.";
		return false;
	}
	if (MIB_REGISTERED_OK != initialize_table_gomiPluginPerformanceTable()) {
		LOG(ERROR) << "gomiPluginPerformanceTable registration: see SNMP log for further details.";
		return false;
	}
	if (MIB_REGISTERED_OK != initialize_table_gomiSessionTable()) {
		LOG(ERROR) << "gomiSessionTable registration: see SNMP log for further details.";
		return false;
	}
	if (MIB_REGISTERED_OK != initialize_table_gomiSessionPerformanceTable()) {
		LOG(ERROR) << "gomiSessionPerformanceTable registration: see SNMP log for further details.";
		return false;
	}
	return true;
}

/* Initialize the gomiPluginTable table by defining its contents and how it's structured.
 */
static
int
initialize_table_gomiPluginTable(void)
{
	DLOG(INFO) << "initialize_table_gomiPluginTable()";

	static const oid gomiPluginTable_oid[] = {1,3,6,1,4,1,67,1,1,2};
	const size_t gomiPluginTable_oid_len = OID_LENGTH (gomiPluginTable_oid);
	netsnmp_handler_registration* reg = nullptr;
	netsnmp_iterator_info* iinfo = nullptr;
	netsnmp_table_registration_info* table_info = nullptr;

	reg = netsnmp_create_handler_registration (
		"gomiPluginTable",	gomiPluginTable_handler,
		gomiPluginTable_oid,	gomiPluginTable_oid_len,
		HANDLER_CAN_RONLY
		);
	if (nullptr == reg)
		goto error;

	table_info = SNMP_MALLOC_TYPEDEF (netsnmp_table_registration_info);
	if (nullptr == table_info)
		goto error;
	netsnmp_table_helper_add_indexes (table_info,
					  ASN_OCTET_STR,  /* index: gomiPluginId */
					  ASN_UNSIGNED,  /* index: gomiPluginInstance */
					  0);
	table_info->min_column = COLUMN_GOMIPLUGINWINDOWSREGISTRYKEY;
	table_info->max_column = COLUMN_GOMIPLUGINRICSUFFIX;
    
	iinfo = SNMP_MALLOC_TYPEDEF (netsnmp_iterator_info);
	if (nullptr == iinfo)
		goto error;
	iinfo->get_first_data_point	= gomiPluginTable_get_first_data_point;
	iinfo->get_next_data_point	= gomiPluginTable_get_next_data_point;
	iinfo->free_loop_context_at_end	= gomiPluginTable_free_loop_context;
	iinfo->table_reginfo		= table_info;
    
	return netsnmp_register_table_iterator (reg, iinfo);

error:
	if (table_info && table_info->indexes)		/* table_data_free_func() is internal */
		snmp_free_var (table_info->indexes);
	SNMP_FREE (table_info);
	SNMP_FREE (iinfo);
	netsnmp_handler_registration_free (reg);
	return -1;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
static 
netsnmp_variable_list*
gomiPluginTable_get_first_data_point (
	void**			my_loop_context,	/* valid through one query of multiple "data points" */
	void**			my_data_context,	/* answer blob which is passed to handler() */
	netsnmp_variable_list*	put_index_data,		/* answer */
	netsnmp_iterator_info*	mydata			/* iinfo on init() */
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginTable_get_first_data_point()";

/* Create our own context for this SNMP loop, lock on list follows lifetime of context */
	std::shared_ptr<snmp_context_t> context (new snmp_context_t (gomi::gomi_t::global_list_lock_, gomi::gomi_t::global_list_));
	if (!(bool)context || context->gomi_list.empty()) {
		DLOG(INFO) << "No instances";
		return nullptr;
	}

/* Save context with NET-SNMP iterator. */
	*my_loop_context = context.get();
	snmp_context_t::global_list.push_back (std::move (context));

/* pass on for generic row access */
	return gomiPluginTable_get_next_data_point (my_loop_context, my_data_context, put_index_data,  mydata);
}

static
netsnmp_variable_list*
gomiPluginTable_get_next_data_point (
	void**			my_loop_context,
	void**			my_data_context,
	netsnmp_variable_list*	put_index_data,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginTable_get_next_data_point()";

	snmp_context_t* context = static_cast<snmp_context_t*>(*my_loop_context);
	netsnmp_variable_list *idx = put_index_data;

/* end of data points */
	if (context->gomi_it == context->gomi_list.end()) {
		DLOG(INFO) << "End of plugin instances.";
		return nullptr;
	}

/* this plugin instance as a data point */
	const gomi::gomi_t* gomi = *context->gomi_it++;

/* gomiPluginId */
	snmp_set_var_typed_value (idx, ASN_OCTET_STR, (const u_char*)gomi->plugin_id_.c_str(), gomi->plugin_id_.length());
        idx = idx->next_variable;

/* gomiPluginInstance */
	const unsigned instance = gomi->instance_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&instance, sizeof (instance));

/* reference remains in list */
        *my_data_context = (void*)gomi;
        return put_index_data;
}

static
void
gomiPluginTable_free_loop_context (
	void*			my_loop_context,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginTable_free_loop_context ()";

/* delete context and shared lock on global list of all gomi objects */
	snmp_context_t* context = static_cast<snmp_context_t*>(my_loop_context);
/* I'm sure there must be a better method :-( */
	snmp_context_t::global_list.erase (std::remove_if (snmp_context_t::global_list.begin(),
		snmp_context_t::global_list.end(),
		[context](std::shared_ptr<snmp_context_t>& shared_context) -> bool {
			return shared_context.get() == context;
	}));
}

/* handles requests for the gomiPluginTable table
 */
static
int
gomiPluginTable_handler (
	netsnmp_mib_handler*		handler,
	netsnmp_handler_registration*	reginfo,
	netsnmp_agent_request_info*	reqinfo,
	netsnmp_request_info*		requests
	)
{
	assert (nullptr != handler);
	assert (nullptr != reginfo);
	assert (nullptr != reqinfo);
	assert (nullptr != requests);

	DLOG(INFO) << "gomiPluginTable_handler()";

	switch (reqinfo->mode) {

/* Read-support (also covers GetNext requests) */

	case MODE_GET:
		for (netsnmp_request_info* request = requests;
		     request;
		     request = request->next)
		{
			const gomi::gomi_t* gomi = static_cast<gomi::gomi_t*>(netsnmp_extract_iterator_context (request));
			if (nullptr == gomi) {
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHINSTANCE);
				continue;
			}

			netsnmp_variable_list* var = request->requestvb;
			netsnmp_table_request_info* table_info = netsnmp_extract_table_info (request);
			if (nullptr == table_info) {
				snmp_log (__netsnmp_LOG_ERR, "gomiPluginTable_handler: empty table request info.\n");
				continue;
			}
    
			switch (table_info->colnum) {
						
			case COLUMN_GOMIPLUGINWINDOWSREGISTRYKEY:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.key.c_str(), gomi->config_.key.length());
				break;

			case COLUMN_GOMIPLUGINSERVICENAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.service_name.c_str(), gomi->config_.service_name.length());
				break;

			case COLUMN_GOMIPLUGINMONITORNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.monitor_name.c_str(), gomi->config_.monitor_name.length());
				break;

			case COLUMN_GOMIPLUGINEVENTQUEUENAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.event_queue_name.c_str(), gomi->config_.event_queue_name.length());
				break;

			case COLUMN_GOMIPLUGINVENDORNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.vendor_name.c_str(), gomi->config_.vendor_name.length());
				break;

			case COLUMN_GOMIPLUGINPUBLISHIVL:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.interval.c_str(), gomi->config_.interval.length());
				break;

			case COLUMN_GOMIPLUGINTOLERABLEDELAY:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.tolerable_delay.c_str(), gomi->config_.tolerable_delay.length());
				break;

// obsolete
			case COLUMN_GOMIPLUGINRESETTIME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR, (const u_char*)nullptr, 0);
				break;

			case COLUMN_GOMIPLUGINRICSUFFIX:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)gomi->config_.suffix.c_str(), gomi->config_.suffix.length());
				break;

			default:
				snmp_log (__netsnmp_LOG_ERR, "gomiPluginTable_handler: unknown column.\n");
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

	default:
		snmp_log (__netsnmp_LOG_ERR, "gomiPluginTable_handler: unnsupported mode.\n");
		break;
	}
	return SNMP_ERR_NOERROR;
}

/* Initialize the gomiPluginPerformanceTable table by defining its contents and how it's structured
*/
static
int
initialize_table_gomiPluginPerformanceTable(void)
{
	DLOG(INFO) << "initialize_table_gomiPluginPerformanceTable()";

	static const oid gomiPluginPerformanceTable_oid[] = {1,3,6,1,4,1,67,1,1,4};
	const size_t gomiPluginPerformanceTable_oid_len = OID_LENGTH(gomiPluginPerformanceTable_oid);
	netsnmp_handler_registration* reg = nullptr;
	netsnmp_iterator_info* iinfo = nullptr;
	netsnmp_table_registration_info* table_info = nullptr;

	reg = netsnmp_create_handler_registration (
		"gomiPluginPerformanceTable",   gomiPluginPerformanceTable_handler,
		gomiPluginPerformanceTable_oid, gomiPluginPerformanceTable_oid_len,
		HANDLER_CAN_RONLY
		);
	if (nullptr == reg)
		goto error;

	table_info = SNMP_MALLOC_TYPEDEF (netsnmp_table_registration_info);
	if (nullptr == table_info)
		goto error;
	netsnmp_table_helper_add_indexes (table_info,
					  ASN_OCTET_STR,  /* index: gomiPluginPerformanceId */
					  ASN_UNSIGNED,  /* index: gomiPluginPerformanceInstance */
					  0);
	table_info->min_column = COLUMN_GOMITCLQUERYRECEIVED;
	table_info->max_column = COLUMN_GOMILASTMSGSSENT;
    
	iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
	if (nullptr == iinfo)
		goto error;
	iinfo->get_first_data_point	= gomiPluginPerformanceTable_get_first_data_point;
	iinfo->get_next_data_point	= gomiPluginPerformanceTable_get_next_data_point;
	iinfo->free_loop_context_at_end = gomiPluginPerformanceTable_free_loop_context;
	iinfo->table_reginfo		= table_info;
    
	return netsnmp_register_table_iterator (reg, iinfo);

error:
	if (table_info && table_info->indexes)		/* table_data_free_func() is internal */
		snmp_free_var (table_info->indexes);
	SNMP_FREE (table_info);
	SNMP_FREE (iinfo);
	netsnmp_handler_registration_free (reg);
	return -1;
}

/* Example iterator hook routines - using 'get_next' to do most of the work
 */
static
netsnmp_variable_list*
gomiPluginPerformanceTable_get_first_data_point (
	void**			my_loop_context,	/* valid through one query of multiple "data points" */
	void**			my_data_context,	/* answer blob which is passed to handler() */
	netsnmp_variable_list*	put_index_data,		/* answer */
	netsnmp_iterator_info*	mydata			/* iinfo on init() */
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginPerformanceTable_get_first_data_point()";

/* Create our own context for this SNMP loop, lock on list follows lifetime of context */
	std::shared_ptr<snmp_context_t> context (new snmp_context_t (gomi::gomi_t::global_list_lock_, gomi::gomi_t::global_list_));
	if (!(bool)context || context->gomi_list.empty()) {
		DLOG(INFO) << "No instances";
		return nullptr;
	}

/* Save context with NET-SNMP iterator. */
	*my_loop_context = context.get();
	snmp_context_t::global_list.push_back (std::move (context));

/* pass on for generic row access */
	return gomiPluginPerformanceTable_get_next_data_point(my_loop_context, my_data_context, put_index_data, mydata);
}

static
netsnmp_variable_list*
gomiPluginPerformanceTable_get_next_data_point (
	void**			my_loop_context,
	void**			my_data_context,
	netsnmp_variable_list*	put_index_data,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginPerformanceTable_get_next_data_point()";

	snmp_context_t* context = static_cast<snmp_context_t*>(*my_loop_context);
	netsnmp_variable_list *idx = put_index_data;

/* end of data points */
	if (context->gomi_it == context->gomi_list.end()) {
		DLOG(INFO) << "End of instances.";
		return nullptr;
	}

/* this plugin instance as a data point */
	const gomi::gomi_t* gomi = *context->gomi_it++;

/* gomiPluginPerformanceId */
	snmp_set_var_typed_value (idx, ASN_OCTET_STR, (const u_char*)gomi->plugin_id_.c_str(), gomi->plugin_id_.length());
        idx = idx->next_variable;

/* gomiPluginPerformanceInstance */
	const unsigned instance = gomi->instance_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&instance, sizeof (instance));

/* reference remains in list */
        *my_data_context = (void*)gomi;
	return put_index_data;
}

static
void
gomiPluginPerformanceTable_free_loop_context (
	void*			my_loop_context,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiPluginPerformanceTable_free_loop_context()";

/* delete context and shared lock on global list of all gomi objects */
	snmp_context_t* context = static_cast<snmp_context_t*>(my_loop_context);
/* I'm sure there must be a better method :-( */
	snmp_context_t::global_list.erase (std::remove_if (snmp_context_t::global_list.begin(),
		snmp_context_t::global_list.end(),
		[context](std::shared_ptr<snmp_context_t>& shared_context) -> bool {
			return shared_context.get() == context;
	}));
}

/* handles requests for the gomiPluginPerformanceTable table
 */
static
int
gomiPluginPerformanceTable_handler (
	netsnmp_mib_handler*		handler,
	netsnmp_handler_registration*	reginfo,
	netsnmp_agent_request_info*	reqinfo,
	netsnmp_request_info*		requests
	)
{
	assert (nullptr != handler);
	assert (nullptr != reginfo);
	assert (nullptr != reqinfo);
	assert (nullptr != requests);

	DLOG(INFO) << "gomiPluginPerformanceTable_handler()";

	switch (reqinfo->mode) {
        
/* Read-support (also covers GetNext requests) */

	case MODE_GET:
		for (netsnmp_request_info* request = requests;
		     request;
		     request = request->next)
		{
			const gomi::gomi_t* gomi = static_cast<gomi::gomi_t*>(netsnmp_extract_iterator_context (request));
			if (nullptr == gomi) {
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHINSTANCE);
				continue;
			}

			netsnmp_variable_list* var = request->requestvb;
			netsnmp_table_request_info* table_info  = netsnmp_extract_table_info (request);
			if (nullptr == table_info) {
				snmp_log (__netsnmp_LOG_ERR, "gomiPluginPerformanceTable_handler: empty table request info.\n");
				continue;
			}
    
			switch (table_info->colnum) {

			case COLUMN_GOMITCLQUERYRECEIVED:
				{
					const unsigned tcl_query_received = gomi->cumulative_stats_[GOMI_PC_TCL_QUERY_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&tcl_query_received, sizeof (tcl_query_received));
				}
				break;

			case COLUMN_GOMITIMERQUERYRECEIVED:
				{
					const unsigned timer_query_received = gomi->cumulative_stats_[GOMI_PC_TIMER_QUERY_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&timer_query_received, sizeof (timer_query_received));
				}
				break;

			case COLUMN_GOMILASTACTIVITY:
				{
					union {
						uint32_t	uint_value;
						__time32_t	time32_t_value;
					} last_activity;
					last_activity.time32_t_value = (gomi->last_activity_ - kUnixEpoch).total_seconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&last_activity.uint_value, sizeof (last_activity.uint_value));
				}
				break;

			case COLUMN_GOMITCLSVCTIMEMIN:
				{
/* conversion of 64-bit integer */
					unsigned min_svc_time = 0;
					if (!gomi->min_tcl_time_.is_special())
						min_svc_time = (unsigned)gomi->min_tcl_time_.total_milliseconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&min_svc_time, sizeof (min_svc_time));
				}
				break;

			case COLUMN_GOMITCLSVCTIMEMEAN:
				{
					unsigned mean_svc_time = 0;
					if (gomi->cumulative_stats_[GOMI_PC_TCL_QUERY_RECEIVED] > 0)
						mean_svc_time = (unsigned)(gomi->total_tcl_time_.total_milliseconds() / gomi->cumulative_stats_[GOMI_PC_TCL_QUERY_RECEIVED]);
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mean_svc_time, sizeof (mean_svc_time));
				}
				break;

			case COLUMN_GOMITCLSVCTIMEMAX:
				{
					unsigned max_svc_time = 0;
					if (!gomi->max_tcl_time_.is_special())
						max_svc_time = (unsigned)gomi->max_tcl_time_.total_milliseconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&max_svc_time, sizeof (max_svc_time));
				}
				break;

			case COLUMN_GOMITIMERSVCTIMEMIN:
				{
					unsigned min_svc_time = 0;
					if (!gomi->min_refresh_time_.is_special())
						min_svc_time = (unsigned)gomi->min_refresh_time_.total_milliseconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&min_svc_time, sizeof (min_svc_time));
				}
				break;

			case COLUMN_GOMITIMERSVCTIMEMEAN:
				{
					unsigned mean_svc_time = 0;
					if (gomi->cumulative_stats_[GOMI_PC_TIMER_QUERY_RECEIVED] > 0)
						mean_svc_time = (unsigned)(gomi->total_refresh_time_.total_milliseconds() / gomi->cumulative_stats_[GOMI_PC_TIMER_QUERY_RECEIVED]);
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mean_svc_time, sizeof (mean_svc_time));
				}
				break;

			case COLUMN_GOMITIMERSVCTIMEMAX:
				{
					unsigned max_svc_time = 0;
					if (!gomi->max_refresh_time_.is_special())
						max_svc_time = (unsigned)gomi->max_refresh_time_.total_milliseconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&max_svc_time, sizeof (max_svc_time));
				}
				break;

			case COLUMN_GOMIMSGSSENT:
				{
					const unsigned msg_sent = (bool)gomi->provider_ ? gomi->provider_->cumulative_stats_[PROVIDER_PC_MSGS_SENT] : 0;
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&msg_sent, sizeof (msg_sent));
				}
				break;

			case COLUMN_GOMILASTMSGSSENT:
				{
					union {
						uint32_t	uint_value;
						__time32_t	time32_t_value;
					} last_activity;
					last_activity.time32_t_value = (bool)gomi->provider_ ? ((gomi->provider_->last_activity_ - kUnixEpoch).total_seconds()) : 0;
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&last_activity.uint_value, sizeof (last_activity.uint_value));
				}
				break;

			default:
				snmp_log (__netsnmp_LOG_ERR, "gomiPluginPerformanceTable_handler: unknown column.\n");
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

	default:
		snmp_log (__netsnmp_LOG_ERR, "gomiPluginPerformanceTable_handler: unsupported mode.\n");
		break;
    }

    return SNMP_ERR_NOERROR;
}

/* Initialize the gomiSessionTable table by defining its contents and how it's structured.
 */
static
int
initialize_table_gomiSessionTable(void)
{
	DLOG(INFO) << "initialize_table_gomiSessionTable()";

	static const oid gomiSessionTable_oid[] = {1,3,6,1,4,1,67,1,1,5};
	const size_t gomiSessionTable_oid_len = OID_LENGTH (gomiSessionTable_oid);
	netsnmp_handler_registration* reg = nullptr;
	netsnmp_iterator_info* iinfo = nullptr;
	netsnmp_table_registration_info* table_info = nullptr;

	reg = netsnmp_create_handler_registration (
		"gomiSessionTable",	gomiSessionTable_handler,
		gomiSessionTable_oid,	gomiSessionTable_oid_len,
		HANDLER_CAN_RONLY
		);
	if (nullptr == reg)
		goto error;

	table_info = SNMP_MALLOC_TYPEDEF (netsnmp_table_registration_info);
	if (nullptr == table_info)
		goto error;
	netsnmp_table_helper_add_indexes (table_info,
					  ASN_OCTET_STR,  /* index: gomiSessionId */
					  ASN_UNSIGNED,  /* index: gomiSessionPluginInstance */
					  ASN_UNSIGNED,  /* index: gomiSessionUniqueInstance */
					  0);
	table_info->min_column = COLUMN_GOMISESSIONRSSLSERVERS;
	table_info->max_column = COLUMN_GOMISESSIONPUBLISHERNAME;
    
	iinfo = SNMP_MALLOC_TYPEDEF (netsnmp_iterator_info);
	if (nullptr == iinfo)
		goto error;
	iinfo->get_first_data_point	= gomiSessionTable_get_first_data_point;
	iinfo->get_next_data_point	= gomiSessionTable_get_next_data_point;
	iinfo->free_loop_context_at_end	= gomiSessionTable_free_loop_context;
	iinfo->table_reginfo		= table_info;
    
	return netsnmp_register_table_iterator (reg, iinfo);

error:
	if (table_info && table_info->indexes)		/* table_data_free_func() is internal */
		snmp_free_var (table_info->indexes);
	SNMP_FREE (table_info);
	SNMP_FREE (iinfo);
	netsnmp_handler_registration_free (reg);
	return -1;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
static 
netsnmp_variable_list*
gomiSessionTable_get_first_data_point (
	void**			my_loop_context,	/* valid through one query of multiple "data points" */
	void**			my_data_context,	/* answer blob which is passed to handler() */
	netsnmp_variable_list*	put_index_data,		/* answer */
	netsnmp_iterator_info*	mydata			/* iinfo on init() */
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionTable_get_first_data_point()";

/* Create our own context for this SNMP loop, lock on list follows lifetime of context. */
	std::shared_ptr<snmp_context_t> context (new snmp_context_t (gomi::gomi_t::global_list_lock_, gomi::gomi_t::global_list_));
	if (!(bool)context || context->gomi_list.empty()) {
		DLOG(INFO) << "No plugin instances.";
		return nullptr;
	}

/* Find first node, through all plugin instances. */
	for (context->gomi_it = context->gomi_list.begin();
		context->gomi_it != context->gomi_list.end();
		++(context->gomi_it))
	{
/* and through all sessions for each plugin provider. */
		context->session_it = (*context->gomi_it)->provider_->sessions_.begin();
		if (context->session_it != (*context->gomi_it)->provider_->sessions_.end()) {
			break;
		}
	}

/* no node found. */
	if (context->session_it == (*context->gomi_it)->provider_->sessions_.end()) {
		DLOG(INFO) << "No session instances.";
		return nullptr;
	}

/* Save context with NET-SNMP iterator. */
	*my_loop_context = context.get();
	snmp_context_t::global_list.push_back (std::move (context));

/* pass on for generic row access */
	return gomiSessionTable_get_next_data_point (my_loop_context, my_data_context, put_index_data,  mydata);
}

static
netsnmp_variable_list*
gomiSessionTable_get_next_data_point (
	void**			my_loop_context,
	void**			my_data_context,
	netsnmp_variable_list*	put_index_data,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionTable_get_next_data_point()";

	snmp_context_t* context = static_cast<snmp_context_t*>(*my_loop_context);
	netsnmp_variable_list *idx = put_index_data;

/* end of data points */
	if (context->gomi_it == context->gomi_list.end()) {
		DLOG(INFO) << "End of plugin instances.";
		return nullptr;
	}
	if (context->session_it == (*context->gomi_it)->provider_->sessions_.end()) {
		DLOG(INFO) << "End of session instances.";
		return nullptr;
	}

/* this session instance as a data point */
	const gomi::session_t* session = (*context->session_it).get();
	const gomi::gomi_t* gomi = *context->gomi_it;

/* gomiSessionPluginId */
	snmp_set_var_typed_value (idx, ASN_OCTET_STR, (const u_char*)gomi->plugin_id_.c_str(), gomi->plugin_id_.length());
        idx = idx->next_variable;

/* gomiSessionPluginUniqueInstance */
	const unsigned instance = gomi->instance_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&instance, sizeof (instance));
        idx = idx->next_variable;

/* gomiSessionUniqueInstance */
	const unsigned session_instance = session->instance_id_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&session_instance, sizeof (session_instance));

/* hunt for next valid node */
	while (++(context->session_it) == (*context->gomi_it)->provider_->sessions_.end()) {
		if (++(context->gomi_it) == context->gomi_list.end()) {
			break;
		}
		context->session_it = (*context->gomi_it)->provider_->sessions_.begin();
	}

/* reference remains in list */
        *my_data_context = (void*)session;
        return put_index_data;
}

static
void
gomiSessionTable_free_loop_context (
	void*			my_loop_context,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionTable_free_loop_context ()";

/* delete context and shared lock on global list of all gomi objects */
	snmp_context_t* context = static_cast<snmp_context_t*>(my_loop_context);
/* I'm sure there must be a better method :-( */
	snmp_context_t::global_list.erase (std::remove_if (snmp_context_t::global_list.begin(),
		snmp_context_t::global_list.end(),
		[context](std::shared_ptr<snmp_context_t>& shared_context) -> bool {
			return shared_context.get() == context;
	}));
}

/* handles requests for the gomiPluginTable table
 */
static
int
gomiSessionTable_handler (
	netsnmp_mib_handler*		handler,
	netsnmp_handler_registration*	reginfo,
	netsnmp_agent_request_info*	reqinfo,
	netsnmp_request_info*		requests
	)
{
	assert (nullptr != handler);
	assert (nullptr != reginfo);
	assert (nullptr != reqinfo);
	assert (nullptr != requests);

	DLOG(INFO) << "gomiSessionTable_handler()";

	switch (reqinfo->mode) {

/* Read-support (also covers GetNext requests) */

	case MODE_GET:
		for (netsnmp_request_info* request = requests;
		     request;
		     request = request->next)
		{
			const gomi::session_t* session = static_cast<gomi::session_t*>(netsnmp_extract_iterator_context (request));
			if (nullptr == session) {
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHINSTANCE);
				continue;
			}

			netsnmp_variable_list* var = request->requestvb;
			netsnmp_table_request_info* table_info = netsnmp_extract_table_info (request);
			if (nullptr == table_info) {
				snmp_log (__netsnmp_LOG_ERR, "gomiSessionTable_handler: empty table request info.\n");
				continue;
			}

			switch (table_info->colnum) {
						
			case COLUMN_GOMISESSIONRSSLSERVERS:
			{
				const char *rssl_server = "";
				size_t rssl_server_len = 0;
				if (!session->config_.rssl_servers.empty()) {
					std::ostringstream ss;
					for (auto it = session->config_.rssl_servers.begin();
						it != session->config_.rssl_servers.end();
						++it)
					{
						if (it != session->config_.rssl_servers.begin())
							ss << ", ";
						ss << *it;
					}
					rssl_server     = ss.str().c_str();
					rssl_server_len = ss.str().length();
				}
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)rssl_server, rssl_server_len);
				break;
			}

			case COLUMN_GOMISESSIONRSSLDEFAULTPORT:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.rssl_default_port.c_str(), session->config_.rssl_default_port.length());
				break;

			case COLUMN_GOMISESSIONAPPLICATIONID:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.application_id.c_str(), session->config_.application_id.length());
				break;

			case COLUMN_GOMISESSIONINSTANCEID:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.instance_id.c_str(), session->config_.instance_id.length());
				break;

			case COLUMN_GOMISESSIONUSERNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.user_name.c_str(), session->config_.user_name.length());
				break;

			case COLUMN_GOMISESSIONPOSITION:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.position.c_str(), session->config_.position.length());
				break;

			case COLUMN_GOMISESSIONSESSIONNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.session_name.c_str(), session->config_.session_name.length());
				break;

			case COLUMN_GOMISESSIONCONNECTIONNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.connection_name.c_str(), session->config_.connection_name.length());
				break;

			case COLUMN_GOMISESSIONPUBLISHERNAME:
				snmp_set_var_typed_value (var, ASN_OCTET_STR,
					(const u_char*)session->config_.publisher_name.c_str(), session->config_.publisher_name.length());
				break;

			default:
				snmp_log (__netsnmp_LOG_ERR, "gomiSessionTable_handler: unknown column.\n");
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

	default:
		snmp_log (__netsnmp_LOG_ERR, "gomiSessionTable_handler: unnsupported mode.\n");
		break;
	}
	return SNMP_ERR_NOERROR;
}

/* Initialize the gomiSessionPerformanceTable table by defining its contents and how it's structured
*/
static
int
initialize_table_gomiSessionPerformanceTable(void)
{
	DLOG(INFO) << "initialize_table_gomiSessionPerformanceTable()";

	static const oid gomiSessionPerformanceTable_oid[] = {1,3,6,1,4,1,67,1,1,6};
	const size_t gomiSessionPerformanceTable_oid_len = OID_LENGTH(gomiSessionPerformanceTable_oid);
	netsnmp_handler_registration* reg = nullptr;
	netsnmp_iterator_info* iinfo = nullptr;
	netsnmp_table_registration_info* table_info = nullptr;

	reg = netsnmp_create_handler_registration (
		"gomiSessionPerformanceTable",   gomiSessionPerformanceTable_handler,
		gomiSessionPerformanceTable_oid, gomiSessionPerformanceTable_oid_len,
		HANDLER_CAN_RONLY
		);
	if (nullptr == reg)
		goto error;

	table_info = SNMP_MALLOC_TYPEDEF (netsnmp_table_registration_info);
	if (nullptr == table_info)
		goto error;
	netsnmp_table_helper_add_indexes (table_info,
					  ASN_OCTET_STR,  /* index: gomiSessionPerformancePluginId */
					  ASN_UNSIGNED,  /* index: gomiSessionPerformancePluginUniqueInstance */
					  ASN_UNSIGNED,  /* index: gomiSessionPerformanceUniqueInstance */
					  0);
	table_info->min_column = COLUMN_GOMISESSIONLASTACTIVITY;
	table_info->max_column = COLUMN_GOMIMMTLOGINDATASTATE;
    
	iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
	if (nullptr == iinfo)
		goto error;
	iinfo->get_first_data_point	= gomiSessionPerformanceTable_get_first_data_point;
	iinfo->get_next_data_point	= gomiSessionPerformanceTable_get_next_data_point;
	iinfo->free_loop_context_at_end = gomiSessionPerformanceTable_free_loop_context;
	iinfo->table_reginfo		= table_info;
    
	return netsnmp_register_table_iterator (reg, iinfo);

error:
	if (table_info && table_info->indexes)		/* table_data_free_func() is internal */
		snmp_free_var (table_info->indexes);
	SNMP_FREE (table_info);
	SNMP_FREE (iinfo);
	netsnmp_handler_registration_free (reg);
	return -1;
}

/* Example iterator hook routines - using 'get_next' to do most of the work
 */
static
netsnmp_variable_list*
gomiSessionPerformanceTable_get_first_data_point (
	void**			my_loop_context,	/* valid through one query of multiple "data points" */
	void**			my_data_context,	/* answer blob which is passed to handler() */
	netsnmp_variable_list*	put_index_data,		/* answer */
	netsnmp_iterator_info*	mydata			/* iinfo on init() */
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionerformanceTable_get_first_data_point()";

/* Create our own context for this SNMP loop, lock on list follows lifetime of context */
	std::shared_ptr<snmp_context_t> context (new snmp_context_t (gomi::gomi_t::global_list_lock_, gomi::gomi_t::global_list_));
	if (!(bool)context || context->gomi_list.empty()) {
		DLOG(INFO) << "No plugin instances";
		return nullptr;
	}

/* Find first node, through all plugin instances. */
	for (context->gomi_it = context->gomi_list.begin();
		context->gomi_it != context->gomi_list.end();
		++(context->gomi_it))
	{
/* and through all sessions for each plugin provider. */
		context->session_it = (*context->gomi_it)->provider_->sessions_.begin();
		if (context->session_it != (*context->gomi_it)->provider_->sessions_.end()) {
			break;
		}
	}

/* no node found. */
	if (context->session_it == (*context->gomi_it)->provider_->sessions_.end()) {
		DLOG(INFO) << "No session instances.";
		return nullptr;
	}

/* Save context with NET-SNMP iterator. */
	*my_loop_context = context.get();
	snmp_context_t::global_list.push_back (std::move (context));

/* pass on for generic row access */
	return gomiSessionPerformanceTable_get_next_data_point(my_loop_context, my_data_context, put_index_data, mydata);
}

static
netsnmp_variable_list*
gomiSessionPerformanceTable_get_next_data_point (
	void**			my_loop_context,
	void**			my_data_context,
	netsnmp_variable_list*	put_index_data,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != my_data_context);
	assert (nullptr != put_index_data);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionPerformanceTable_get_next_data_point()";

	snmp_context_t* context = static_cast<snmp_context_t*>(*my_loop_context);
	netsnmp_variable_list *idx = put_index_data;

/* end of data points */
	if (context->gomi_it == context->gomi_list.end()) {
		DLOG(INFO) << "End of plugin instances.";
		return nullptr;
	}
	if (context->session_it == (*context->gomi_it)->provider_->sessions_.end()) {
		DLOG(INFO) << "End of session instances.";
		return nullptr;
	}

/* this plugin instance as a data point */
	const gomi::session_t* session = (*context->session_it).get();
	const gomi::gomi_t* gomi = *context->gomi_it;

/* gomiSessionPerformancePluginId */
	snmp_set_var_typed_value (idx, ASN_OCTET_STR, (const u_char*)gomi->plugin_id_.c_str(), gomi->plugin_id_.length());
        idx = idx->next_variable;

/* gomiSessionPerformancePluginUniqueInstance */
	const unsigned instance = gomi->instance_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&instance, sizeof (instance));
        idx = idx->next_variable;

/* gomiSessionPerformanceUniqueInstance */
	const unsigned session_instance = session->instance_id_;
	snmp_set_var_typed_value (idx, ASN_UNSIGNED, (const u_char*)&session_instance, sizeof (session_instance));

/* hunt for next valid node */
	while (++(context->session_it) == (*context->gomi_it)->provider_->sessions_.end()) {
		if (++(context->gomi_it) == context->gomi_list.end()) {
			break;
		}
		context->session_it = (*context->gomi_it)->provider_->sessions_.begin();
	}

/* reference remains in list */
        *my_data_context = (void*)session;
	return put_index_data;
}

static
void
gomiSessionPerformanceTable_free_loop_context (
	void*			my_loop_context,
	netsnmp_iterator_info*	mydata
	)
{
	assert (nullptr != my_loop_context);
	assert (nullptr != mydata);

	DLOG(INFO) << "gomiSessionPerformanceTable_free_loop_context()";

/* delete context and shared lock on global list of all gomi objects */
	snmp_context_t* context = static_cast<snmp_context_t*>(my_loop_context);
/* I'm sure there must be a better method :-( */
	snmp_context_t::global_list.erase (std::remove_if (snmp_context_t::global_list.begin(),
		snmp_context_t::global_list.end(),
		[context](std::shared_ptr<snmp_context_t>& shared_context) -> bool {
			return shared_context.get() == context;
	}));
}

/* handles requests for the gomiSessionPerformanceTable table
 */
static
int
gomiSessionPerformanceTable_handler (
	netsnmp_mib_handler*		handler,
	netsnmp_handler_registration*	reginfo,
	netsnmp_agent_request_info*	reqinfo,
	netsnmp_request_info*		requests
	)
{
	assert (nullptr != handler);
	assert (nullptr != reginfo);
	assert (nullptr != reqinfo);
	assert (nullptr != requests);

	DLOG(INFO) << "gomiSessionPerformanceTable_handler()";

	switch (reqinfo->mode) {
        
/* Read-support (also covers GetNext requests) */

	case MODE_GET:
		for (netsnmp_request_info* request = requests;
		     request;
		     request = request->next)
		{
			const gomi::session_t* session = static_cast<gomi::session_t*>(netsnmp_extract_iterator_context (request));
			if (nullptr == session) {
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHINSTANCE);
				continue;
			}

			netsnmp_variable_list* var = request->requestvb;
			netsnmp_table_request_info* table_info  = netsnmp_extract_table_info (request);
			if (nullptr == table_info) {
				snmp_log (__netsnmp_LOG_ERR, "gomiSessionPerformanceTable_handler: empty table request info.\n");
				continue;
			}
    
			switch (table_info->colnum) {

			case COLUMN_GOMISESSIONLASTACTIVITY:
				{
					union {
						uint32_t	uint_value;
						__time32_t	time32_t_value;
					} last_activity;
					last_activity.time32_t_value = (session->last_activity_ - kUnixEpoch).total_seconds();
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&last_activity.uint_value, sizeof (last_activity.uint_value));
				}
				break;

			case COLUMN_GOMISESSIONRFAMSGSSENT:
				{
					const unsigned rfa_msg_sent = session->cumulative_stats_[SESSION_PC_RFA_MSGS_SENT];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&rfa_msg_sent, sizeof (rfa_msg_sent));
				}
				break;

			case COLUMN_GOMIRFAEVENTSRECEIVED:
				{
					const unsigned rfa_events_received = session->cumulative_stats_[SESSION_PC_RFA_EVENTS_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&rfa_events_received, sizeof (rfa_events_received));
				}
				break;

			case COLUMN_GOMIRFAEVENTSDISCARDED:
				{
					const unsigned rfa_events_discarded = session->cumulative_stats_[SESSION_PC_RFA_EVENTS_DISCARDED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&rfa_events_discarded, sizeof (rfa_events_discarded));
				}
				break;
            
			case COLUMN_GOMIOMMITEMEVENTSRECEIVED:
				{
					const unsigned omm_item_events_received = session->cumulative_stats_[SESSION_PC_OMM_ITEM_EVENTS_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&omm_item_events_received, sizeof (omm_item_events_received));
				}
				break;

			case COLUMN_GOMIOMMITEMEVENTSDISCARDED:
				{
					const unsigned omm_item_events_discarded = session->cumulative_stats_[SESSION_PC_OMM_ITEM_EVENTS_DISCARDED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&omm_item_events_discarded, sizeof (omm_item_events_discarded));
				}
				break;

			case COLUMN_GOMIRESPONSEMSGSRECEIVED:
				{
					const unsigned response_msgs_received = session->cumulative_stats_[SESSION_PC_RESPONSE_MSGS_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&response_msgs_received, sizeof (response_msgs_received));
				}
				break;

			case COLUMN_GOMIRESPONSEMSGSDISCARDED:
				{
					const unsigned response_msgs_discarded = session->cumulative_stats_[SESSION_PC_RESPONSE_MSGS_DISCARDED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&response_msgs_discarded, sizeof (response_msgs_discarded));
				}
				break;

			case COLUMN_GOMIMMTLOGINRESPONSERECEIVED:
				{
					const unsigned mmt_login_responses_received = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_RESPONSE_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_login_responses_received, sizeof (mmt_login_responses_received));
				}
				break;

			case COLUMN_GOMIMMTLOGINRESPONSEDISCARDED:
				{
					const unsigned mmt_login_responses_discarded = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_RESPONSE_DISCARDED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_login_responses_discarded, sizeof (mmt_login_responses_discarded));
				}
				break;

			case COLUMN_GOMIMMTLOGINSUCCESSRECEIVED:
				{
					const unsigned mmt_login_success_received = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_SUCCESS_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_login_success_received, sizeof (mmt_login_success_received));
				}
				break;

			case COLUMN_GOMIMMTLOGINSUSPECTRECEIVED:
				{
					const unsigned mmt_login_suspect_received = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_SUSPECT_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_login_suspect_received, sizeof (mmt_login_suspect_received));
				}
				break;

			case COLUMN_GOMIMMTLOGINCLOSEDRECEIVED:
				{
					const unsigned mmt_login_closed_received = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_CLOSED_RECEIVED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_login_closed_received, sizeof (mmt_login_closed_received));
				}
				break;

			case COLUMN_GOMIOMMCMDERRORS:
				{
					const unsigned omm_cmd_errors = session->cumulative_stats_[SESSION_PC_OMM_CMD_ERRORS];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&omm_cmd_errors, sizeof (omm_cmd_errors));
				}
				break;

			case COLUMN_GOMIMMTLOGINSVALIDATED:
				{
					const unsigned mmt_logins_validated = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_VALIDATED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_logins_validated, sizeof (mmt_logins_validated));
				}
				break;

			case COLUMN_GOMIMMTLOGINSMALFORMED:
				{
					const unsigned mmt_logins_malformed = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_MALFORMED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_logins_malformed, sizeof (mmt_logins_malformed));
				}
				break;

			case COLUMN_GOMIMMTLOGINSSENT:
				{
					const unsigned mmt_logins_sent = session->cumulative_stats_[SESSION_PC_MMT_LOGIN_SENT];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_logins_sent, sizeof (mmt_logins_sent));
				}
				break;

			case COLUMN_GOMIMMTDIRECTORYSVALIDATED:
				{
					const unsigned mmt_directorys_validated = session->cumulative_stats_[SESSION_PC_MMT_DIRECTORY_VALIDATED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_directorys_validated, sizeof (mmt_directorys_validated));
				}
				break;

			case COLUMN_GOMIMMTDIRECTORYSMALFORMED:
				{
					const unsigned mmt_directorys_malformed = session->cumulative_stats_[SESSION_PC_MMT_DIRECTORY_MALFORMED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_directorys_malformed, sizeof (mmt_directorys_malformed));
				}
				break;

			case COLUMN_GOMIMMTDIRECTORYSSENT:
				{
					const unsigned mmt_directorys_sent = session->cumulative_stats_[SESSION_PC_MMT_DIRECTORY_SENT];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&mmt_directorys_sent, sizeof (mmt_directorys_sent));
				}
				break;

			case COLUMN_GOMITOKENSGENERATED:
				{
					const unsigned tokens_generated = session->cumulative_stats_[SESSION_PC_TOKENS_GENERATED];
					snmp_set_var_typed_value (var, ASN_COUNTER, /* ASN_COUNTER32 */
						(const u_char*)&tokens_generated, sizeof (tokens_generated));
				}
				break;

			case COLUMN_GOMIMMTLOGINSTREAMSTATE:
				{
/* 0 = rfa::common::RespStatus::UnspecifiedEnum */
					const int stream_state = session->stream_state_;
					snmp_set_var_typed_value (var, ASN_INTEGER,
						(const u_char*)&stream_state, sizeof (stream_state));
				}
				break;

			case COLUMN_GOMIMMTLOGINDATASTATE:
				{
/* 0 = rfa::common::RespStatus::UnspecifiedStreamStateEnum */
					const int data_state = session->data_state_;
					snmp_set_var_typed_value (var, ASN_INTEGER,
						(const u_char*)&data_state, sizeof (data_state));
				}
				break;

			default:
				snmp_log (__netsnmp_LOG_ERR, "gomiSessionPerformanceTable_handler: unknown column.\n");
				netsnmp_set_request_error (reqinfo, request, SNMP_NOSUCHOBJECT);
				break;
			}
		}
		break;

	default:
		snmp_log (__netsnmp_LOG_ERR, "gomiSessionPerformanceTable_handler: unsupported mode.\n");
		break;
    }

    return SNMP_ERR_NOERROR;
}

} /* namespace gomi */

/* eof */